version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - my-data-volume:/data/db

  springapp:
    image: my-spring-boot-app2:latest
    container_name: springapp
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://my-mongo-container:27017/mydatabase

volumes:
  my-data-volume:
    driver: local
